#!/usr/bin/env node
/**
 * install.mjs — my-automaton One-Command CLI Installer
 * 
 * Run: curl -sL https://automation.songheng.vip/install.mjs | node
 * Or:  npx @my-automaton/cli
 * 
 * Installs CLI, generates dev API key, and tests connectivity.
 * Works even when tunnel is down (connects via localhost or direct IP).
 */

const BASE_URLS = [
  'https://automation.songheng.vip',
  'http://automation.songheng.vip:8080',
  'http://127.0.0.1:8080'
];

async function testConnection() {
  for (const url of BASE_URLS) {
    try {
      const resp = await fetch(`${url}/health`);
      if (resp.ok) {
        console.log(`✅ Connected to: ${url}`);
        return url;
      }
    } catch(e) {
      // Try next URL
    }
  }
  return null;
}

async function generateDevKey(baseUrl) {
  try {
    const resp = await fetch(`${baseUrl}/api/dev-key`, { method: 'POST' });
    if (resp.ok) {
      const data = await resp.json();
      return data.apiKey;
    }
  } catch(e) {
    // Dev key endpoint might not be available
  }
  
  // Fallback: use a default dev key
  return 'am_dev_install_0000000000';
}

async function install() {
  console.log(`
╔══════════════════════════════════════════╗
║     🚀 my-automaton CLI Installer       ║
║   AI Code Review & Text Analysis API    ║
╚══════════════════════════════════════════╝
`);

  // 1. Test connectivity
  console.log('🔍 Testing connectivity...');
  const baseUrl = await testConnection();
  if (!baseUrl) {
    console.log('⚠️  Could not reach any my-automaton server.');
    console.log('   Using offline mode — some features may be unavailable.');
  } else {
    console.log(`   Service online at ${baseUrl}`);
  }

  // 2. Get API key
  console.log('\n🔑 Getting your API key...');
  let apiKey = process.env.MY_AUTOMATON_KEY;
  if (apiKey) {
    console.log('   Using existing key from MY_AUTOMATON_KEY env var');
  } else if (baseUrl) {
    apiKey = await generateDevKey(baseUrl);
    if (apiKey && !apiKey.includes('fallback')) {
      console.log(`   ✅ Dev key generated: ${apiKey}`);
    } else {
      apiKey = 'am_dev_' + Math.random().toString(36).slice(2, 10);
      console.log(`   ✅ Local key generated: ${apiKey}`);
    }
  } else {
    apiKey = 'am_dev_' + Math.random().toString(36).slice(2, 10);
    console.log(`   ✅ Local key: ${apiKey} (offline mode)`);
  }

  // 3. Create the CLI script
  const cliScript = `#!/usr/bin/env node
// my-automaton CLI — AI Code Review & Text Analysis
// Generated by install.mjs

const API_KEY = '${apiKey}';
const BASE = '${baseUrl || BASE_URLS[0]}';

async function callAPI(endpoint, data) {
  const resp = await fetch(\`\${BASE}\${endpoint}\`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-API-Key': API_KEY
    },
    body: JSON.stringify(data)
  });
  
  if (resp.status === 402) {
    console.log('💳 Credits exhausted — purchase more at:', BASE);
    process.exit(1);
  }
  
  return resp.json();
}

const [,, cmd, ...args] = process.argv;
const HELP = \`
Usage: npx my-automaton <command> [input]

Commands:
  review <file|code>     AI code review
  security <file|code>   Security vulnerability scan
  analyze <text>         Deep text analysis
  summarize <text>       AI summarization
  explain <file|code>    Code explanation
  refactor <file|code>   Refactoring suggestions
  complexity <file|code> Complexity analysis
  help                   Show this help

Examples:
  npx my-automaton review myfile.js
  npx my-automaton security "eval(document.cookie)"
  npx my-automaton analyze "Long text to analyze..."
  echo "my code" | npx my-automaton review

Free tier: 3 requests/day/IP. Upgrade for unlimited use.
\`;

if (!cmd || cmd === 'help') {
  console.log(HELP);
  process.exit(0);
}

const endpoints = {
  review: '/v1/review',
  security: '/v1/security', 
  analyze: '/v1/analyze',
  summarize: '/v1/summarize',
  explain: '/v1/explain',
  refactor: '/v1/refactor',
  complexity: '/v1/complexity'
};

const endpoint = endpoints[cmd];
if (!endpoint) {
  console.log('Unknown command:', cmd);
  console.log(HELP);
  process.exit(1);
}

async function main() {
  let input = args.join(' ');
  
  // If no args, try reading from stdin
  if (!input && !process.stdin.isTTY) {
    const chunks = [];
    for await (const chunk of process.stdin) chunks.push(chunk);
    input = Buffer.concat(chunks).toString().trim();
  }
  
  if (!input) {
    console.log('Please provide input (file path, code, or text)');
    console.log(\`Usage: npx my-automaton \${cmd} "your input"\`);
    process.exit(1);
  }
  
  // Check if input is a file path
  try {
    const fs = await import('fs');
    if (fs.existsSync(input)) {
      input = fs.readFileSync(input, 'utf8');
    }
  } catch(e) {}
  
  const data = {};
  if (['review', 'security', 'explain', 'refactor', 'complexity'].includes(cmd)) {
    data.code = input;
    data.language = args.find(a => a.startsWith('--lang='))?.split('=')[1] || 'auto';
  } else {
    data.text = input;
  }
  
  try {
    const result = await callAPI(endpoint, data);
    console.log(JSON.stringify(result, null, 2));
  } catch(e) {
    console.error('Error:', e.message);
  }
}

main();
`;

  fs.writeFileSync('/usr/local/bin/my-automaton', cliScript);
  fs.chmodSync('/usr/local/bin/my-automaton', 0o755);

  console.log('\n📦 Installing CLI...');
  console.log('   ✅ /usr/local/bin/my-automaton');

  // 4. Test the CLI
  console.log('\n🧪 Testing CLI...');
  const { execSync } = await import('child_process');
  try {
    const help = execSync('my-automaton help', { encoding: 'utf8' });
    console.log('   ✅ CLI installed and working');
    console.log('');
    console.log(help.split('\n').slice(0, 5).join('\n'));
  } catch(e) {
    console.log('   ⚠️  CLI installed but test failed:', e.message);
  }

  // 5. Summary
  console.log('\n╔══════════════════════════════════════════╗');
  console.log('║      ✅ Installation Complete!          ║');
  console.log('╠══════════════════════════════════════════╣');
  console.log(`║  CLI:     my-automaton <command>         ║`);
  console.log(`║  API Key: ${apiKey.slice(0, 16)}...         ║`);
  console.log(`║  Server:  ${baseUrl || 'offline'}        ║`);
  console.log('╠══════════════════════════════════════════╣');
  console.log('║  Try:                                    ║');
  console.log('║  my-automaton review "function hello()"  ║');
  console.log('║  my-automaton security myfile.js         ║');
  console.log('║  my-automaton analyze "long text here"   ║');
  console.log('╚══════════════════════════════════════════╝');
}

import fs from 'fs';
install().catch(e => console.error('Install failed:', e.message));
