#!/usr/bin/env node
/**
 * gateway-patcher.mjs — ONE-SHOT patch all missing routes into gateway.cjs
 * 
 * Adds routes for:
 * - /tools/json-formatter, /tools/json-to-typescript, /tools/http-status-codes
 * - /demo, /install.sh
 * - /blog/* (all 104+ blog posts)
 * - /api/badge/:label/:grade/:score
 * - /api/free/* endpoints (analyze, summarize, review, security, explain, refactor, complexity)
 * - /api/traffic, /api/stats/* 
 * 
 * Run: node /root/automaton/scripts/gateway-patcher.mjs
 * Then: (host) sudo systemctl restart automaton-gateway
 */

import fs from 'fs';

const GATEWAY = '/root/automaton/gateway.cjs';
const CONTENT = '/root/automaton/content';
const BACKUP = GATEWAY + '.patcher-backup';

// Read current gateway
const src = fs.readFileSync(GATEWAY, 'utf-8');

// Make backup
fs.copyFileSync(GATEWAY, BACKUP);
console.log(`✅ Backup saved to ${BACKUP}`);

// ─── Build route additions ───

// 1. Static content routes (blog posts, tools, etc.)
function getAllHtmlFiles(dir, prefix = '') {
  const results = [];
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const e of entries) {
      const fp = dir + '/' + e.name;
      const rp = prefix ? prefix + '/' + e.name : e.name;
      if (e.isDirectory()) results.push(...getAllHtmlFiles(fp, rp));
      else if (e.name.endsWith('.html')) results.push({ route: '/' + rp, file: rp });
    }
  } catch {}
  return results;
}

const htmlFiles = getAllHtmlFiles(CONTENT);
console.log(`Found ${htmlFiles.length} HTML files`);

// 2. Generate static route blocks
const staticRoutes = htmlFiles
  .filter(f => !f.route.startsWith('/index.html') && !f.route.startsWith('/data/'))
  .map(f => {
    const route = f.route
      .replace('/index.html', '/')
      .replace(/\/index\.html$/, '/');
    const filePath = '/root/automaton/content/' + f.file;
    return `  app.get('${route}', (q,r) => r.sendFile('${filePath}'));`;
  })
  .join('\n');

// 3. Generate the static routes insertion point
// We need to find the right place in gateway.cjs to insert routes
// Look for a pattern like app.get('/' or similar route definitions

// Strategy: Insert after the last static route definition, before API routes
// Or simpler: find a unique marker and add routes before the server startup

let patched = src;

// Find the server startup section
const listenPattern = /app\.listen\(/;
const listenMatch = src.match(listenPattern);

if (listenMatch) {
  const insertPos = listenMatch.index;
  
  const routeBlock = `
// ─── Auto-generated static routes (104+ pages) ───
// Generated by gateway-patcher.mjs on ${new Date().toISOString()}
${staticRoutes}

// ─── API free routes ───
app.post('/api/free/analyze', async (q, r) => {
  try { const { text } = q.body || {}; if (!text) return r.status(400).json({error:'text required'}); const result = await callDeepSeek('analyze', text); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/summarize', async (q, r) => {
  try { const { text, maxLength } = q.body || {}; if (!text) return r.status(400).json({error:'text required'}); const result = await callDeepSeek('summarize', text, {maxLength:maxLength||150}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/review', async (q, r) => {
  try { const { code, language } = q.body || {}; if (!code) return r.status(400).json({error:'code required'}); const result = await callDeepSeek('review', code, {language:language||'javascript'}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/security', async (q, r) => {
  try { const { code, language } = q.body || {}; if (!code) return r.status(400).json({error:'code required'}); const result = await callDeepSeek('security', code, {language:language||'javascript'}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/explain', async (q, r) => {
  try { const { code, language } = q.body || {}; if (!code) return r.status(400).json({error:'code required'}); const result = await callDeepSeek('explain', code, {language:language||'javascript'}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/refactor', async (q, r) => {
  try { const { code, language } = q.body || {}; if (!code) return r.status(400).json({error:'code required'}); const result = await callDeepSeek('refactor', code, {language:language||'javascript'}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});
app.post('/api/free/complexity', async (q, r) => {
  try { const { code, language } = q.body || {}; if (!code) return r.status(400).json({error:'code required'}); const result = await callDeepSeek('complexity', code, {language:language||'javascript'}); r.json({result}); } catch(e) { r.status(500).json({error:e.message}); }
});

// ─── Traffic & stats ───
app.get('/api/traffic', (q, r) => {
  try { const data = JSON.parse(fs.readFileSync('/root/automaton/data/traffic.json','utf-8')); r.json(data); } catch(e) { r.json({requests:0,totalRevenue:0,byPath:{}}); }
});
app.get('/api/stats/overview', (q, r) => {
  try {
    const apiKeys = JSON.parse(fs.readFileSync('/root/automaton/api-keys.json','utf-8'));
    let totalCredits = 0, totalUsed = 0, totalRevenue = 0;
    for (const k of Object.values(apiKeys)) { totalCredits += k.credits||0; totalUsed += k.used||0; }
    const traffic = JSON.parse(fs.readFileSync('/root/automaton/data/traffic.json','utf-8'));
    r.json({
      totalRequests: traffic.requests || 0,
      totalApiKeys: Object.keys(apiKeys).length,
      totalCreditsIssued: totalCredits,
      totalCreditsUsed: totalUsed,
      totalRevenue: totalRevenue,
      status: 'running'
    });
  } catch(e) { r.json({totalRequests:0,totalApiKeys:0,totalCreditsIssued:0,totalCreditsUsed:0,totalRevenue:0,status:'error',error:e.message}); }
});

// ─── Badge service ───
app.get('/api/badge/:label/:grade/:score', (q, r) => {
  const { label, grade, score } = q.params;
  const colors = {A:'#3fb950',B:'#d29922',C:'#f0883e',D:'#f85149',F:'#da3633'};
  const color = colors[grade] || '#8b949e';
  const svg = \`<svg xmlns="http://www.w3.org/2000/svg" width="\${label.length*8+90}" height="20">
    <linearGradient id="s" x2="0" y2="1"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
    <rect rx="3" width="\${label.length*8+30}" height="20" fill="#555"/>
    <rect rx="3" x="\${label.length*8+30}" width="60" height="20" fill="\${color}"/>
    <rect rx="3" width="\${label.length*8+30}" height="20" fill="#555"/><rect x="\${label.length*8+30}" width="60" height="20" fill="\${color}"/>
    <rect fill="\${color}" x="\${label.length*8+30}" width="60" height="20"/>
    <g fill="#fff" font-family="DejaVu Sans,sans-serif" font-size="11">
      <text x="\${label.length*4+15}" y="15" fill="#010101" fill-opacity=".3">\${label}</text>
      <text x="\${label.length*4+15}" y="14">\${label}</text>
      <text x="\${label.length*8+60}" y="15" fill="#010101" fill-opacity=".3">\${grade}</text>
      <text x="\${label.length*8+60}" y="14">\${grade}</text>
    </g>
  </svg>\`;
  r.setHeader('Content-Type','image/svg+xml');
  r.setHeader('Cache-Control','public,max-age=3600');
  r.send(svg);
});

// ─── Install.sh (raw text) ───
app.get('/install.sh', (q, r) => {
  r.setHeader('Content-Type','text/plain');
  r.sendFile('/root/automaton/content/install.sh');
});
app.get('/robots.txt', (q, r) => {
  r.setHeader('Content-Type','text/plain');
  r.send(\`User-agent: *\\nAllow: /\\nSitemap: https://automation.songheng.vip/sitemap.xml\\n\`);
});
app.get('/sitemap.xml', (q, r) => {
  r.setHeader('Content-Type','application/xml');
  r.sendFile('/root/automaton/content/sitemap.xml');
});

`;
  
  patched = src.slice(0, insertPos) + routeBlock + src.slice(insertPos);
  fs.writeFileSync(GATEWAY, patched);
  console.log(`✅ Patched ${GATEWAY} with ${htmlFiles.length} static routes + API endpoints`);
  console.log(`   Routes added before 'app.listen('`);
  console.log(`   Execute: sudo systemctl restart automaton-gateway (on host)`);
} else {
  console.log('❌ Could not find app.listen() in gateway.cjs');
  process.exit(1);
}

// ─── Write a signal file the host can detect ───
fs.writeFileSync('/tmp/gateway-needs-restart', new Date().toISOString());
console.log(`✅ Signal file written to /tmp/gateway-needs-restart`);
console.log('');
console.log('─── NEXT STEPS ───');
console.log('1. On HOST: sudo systemctl restart automaton-gateway');
console.log('2. Verify: curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/tools/json-formatter');
console.log('3. If patcher broke the gateway, restore backup:');
console.log(`   cp ${BACKUP} ${GATEWAY} && sudo systemctl restart automaton-gateway`);
